spring.application.name=auth-service
server.port=8084
spring.application.name=auth-service

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bankdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:finbank}
spring.datasource.password=${DB_PASSWORD:finbank}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

jwt.secret=${JWT_SECRET:finbank-development-secret-change-before-deployment-1234567890}
jwt.expiration=3600000
